const puppeteer = require('puppeteer');

const NAVY = '#1B2A4A';
const GOLD = '#C9A84C';

const FIRM = {
  name: 'J Brantley Law',
  attorney: 'Jennifer N. Brantley, Esq.',
  phone: '(210) 742-2435',
  email: 'jbrantley@jenniferbrantleylaw.com',
  website: 'jenniferbrantleylaw.com',
};

const fmt$ = (n) => Number(n || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—';

function firmHeader() {
  return `
    <div style="display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid ${GOLD};padding-bottom:12px;margin-bottom:20px;">
      <div>
        <div style="font-family:Georgia,serif;font-size:22px;font-weight:bold;color:${NAVY};">${FIRM.name}</div>
        <div style="font-size:12px;color:${NAVY};margin-top:2px;">${FIRM.attorney}</div>
        <div style="font-size:11px;color:#666;margin-top:2px;">${FIRM.phone} &nbsp;|&nbsp; ${FIRM.email}</div>
      </div>
      <div style="text-align:right;font-size:11px;color:#888;">
        <div>${FIRM.website}</div>
      </div>
    </div>`;
}

const baseHtml = (title, body) => `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: 'Georgia', serif; font-size: 10.5pt; color: #222; margin: 0; padding: 36px 52px; line-height: 1.55; }
    h2   { font-size: 13pt; color: ${NAVY}; margin: 18px 0 6px; border-bottom: 1px solid #e9ecef; padding-bottom: 4px; }
    h3   { font-size: 11pt; color: ${NAVY}; margin: 14px 0 4px; }
    p    { margin: 0 0 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 10pt; }
    th   { background: ${NAVY}; color: #fff; padding: 6px 10px; text-align: left; font-size: 9pt; }
    td   { padding: 6px 10px; border-bottom: 1px solid #f1f3f5; }
    .total-row td { font-weight: bold; border-top: 2px solid ${NAVY}; background: #f8f9fa; }
    .badge-paid    { color: #166534; background: #dcfce7; padding: 2px 8px; border-radius: 10px; font-size: 9pt; font-weight: bold; }
    .badge-unpaid  { color: #9b2c2c; background: #fff5f5; padding: 2px 8px; border-radius: 10px; font-size: 9pt; font-weight: bold; }
    .badge-partial { color: #92400e; background: #fef3c7; padding: 2px 8px; border-radius: 10px; font-size: 9pt; font-weight: bold; }
    .field  { display:flex; gap: 8px; margin-bottom: 4px; font-size: 10pt; }
    .label  { color: #6c757d; min-width: 130px; }
  </style>
</head>
<body>
  ${firmHeader()}
  ${body}
  <div style="margin-top:40px;font-size:8.5pt;color:#aaa;border-top:1px solid #eee;padding-top:6px;">
    Generated by J Brantley Law Case Management System &bull; ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

async function renderPdf(html) {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    return await page.pdf({
      format: 'Letter',
      margin: { top: '0.75in', bottom: '0.75in', left: '0.75in', right: '0.75in' },
      printBackground: true,
    });
  } finally {
    await browser.close();
  }
}

async function generateInvoicePdf(invoice) {
  const statusClass = invoice.status === 'paid' ? 'paid' : invoice.status === 'partial' ? 'partial' : 'unpaid';
  const balance = Number(invoice.total_amount || 0) - Number(invoice.amount_paid || 0);

  const lineRows = (invoice.line_items || []).map(li => `
    <tr>
      <td>${li.description}</td>
      <td style="text-align:center;">${Number(li.quantity || 1).toFixed(2)}</td>
      <td style="text-align:right;">${fmt$(li.rate)}</td>
      <td style="text-align:right;">${fmt$(li.amount)}</td>
    </tr>`).join('');

  const body = `
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;">
      <div>
        <div style="font-size:20pt;font-weight:bold;color:${NAVY};">INVOICE</div>
        <div style="font-size:11pt;color:#6c757d;">No. ${String(invoice.invoice_number).padStart(4,'0')}</div>
      </div>
      <div style="text-align:right;">
        <span class="badge-${statusClass}">${invoice.status?.toUpperCase()}</span>
        <div style="font-size:10pt;color:#6c757d;margin-top:6px;">Invoice Date: ${fmtDate(invoice.invoice_date)}</div>
        ${invoice.due_date ? `<div style="font-size:10pt;color:#6c757d;">Due Date: ${fmtDate(invoice.due_date)}</div>` : ''}
      </div>
    </div>

    <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px;">
      <div>
        <h3>Bill To</h3>
        <div style="font-weight:bold;">${invoice.client_name || '—'}</div>
        ${invoice.client_email ? `<div style="font-size:10pt;color:#6c757d;">${invoice.client_email}</div>` : ''}
        ${invoice.client_phone ? `<div style="font-size:10pt;color:#6c757d;">${invoice.client_phone}</div>` : ''}
      </div>
      <div>
        <h3>Matter</h3>
        <div style="font-weight:bold;">${invoice.matter_number || '—'}</div>
        <div style="font-size:10pt;color:#6c757d;">${invoice.matter_name || ''}</div>
        <div style="font-size:10pt;color:#6c757d;">${invoice.practice_area || ''}</div>
      </div>
    </div>

    <table>
      <thead><tr><th>Description</th><th style="text-align:center;">Qty/Hrs</th><th style="text-align:right;">Rate</th><th style="text-align:right;">Amount</th></tr></thead>
      <tbody>
        ${lineRows}
        <tr class="total-row">
          <td colspan="3" style="text-align:right;">Total</td>
          <td style="text-align:right;">${fmt$(invoice.total_amount)}</td>
        </tr>
        ${Number(invoice.amount_paid) > 0 ? `
        <tr class="total-row" style="color:#166534;">
          <td colspan="3" style="text-align:right;">Amount Paid</td>
          <td style="text-align:right;">(${fmt$(invoice.amount_paid)})</td>
        </tr>
        <tr class="total-row" style="font-size:12pt;">
          <td colspan="3" style="text-align:right;">Balance Due</td>
          <td style="text-align:right;color:${balance > 0 ? '#c53030' : '#166534'};">${fmt$(balance)}</td>
        </tr>` : ''}
      </tbody>
    </table>

    ${invoice.notes ? `<div style="margin-top:20px;padding:10px 14px;background:#f8f9fa;border-left:3px solid ${GOLD};font-size:10pt;"><strong>Notes:</strong> ${invoice.notes}</div>` : ''}
    ${invoice.payment_method ? `<p style="margin-top:10px;font-size:10pt;color:#6c757d;">Payment method: ${invoice.payment_method}</p>` : ''}

    <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e9ecef;font-size:9.5pt;color:#888;text-align:center;">
      Thank you for trusting J Brantley Law. Questions? Contact us at ${FIRM.phone} or ${FIRM.email}
    </div>`;

  return renderPdf(baseHtml('Invoice', body));
}

async function generateMatterSummaryPdf(matter) {
  const field = (label, val) =>
    `<div class="field"><span class="label">${label}</span><span>${val || '—'}</span></div>`;

  const body = `
    <div style="margin-bottom:20px;">
      <div style="font-size:16pt;font-weight:bold;color:${NAVY};">${matter.matter_number}</div>
      <div style="font-size:13pt;color:#333;margin-top:2px;">${matter.matter_name}</div>
    </div>

    <h2>Client Information</h2>
    ${field('Name', matter.client_name)}
    ${field('Email', matter.client_email)}
    ${field('Phone', matter.client_phone)}
    ${field('Address', matter.client_address)}
    ${field('Company', matter.client_company)}

    <h2>Matter Information</h2>
    ${field('Matter Number', matter.matter_number)}
    ${field('Practice Area', matter.practice_area)}
    ${field('Status', matter.status?.toUpperCase())}
    ${field('Open Date', fmtDate(matter.open_date))}
    ${field('Assigned Staff', matter.assigned_name)}
    ${field('Description', matter.description)}

    <h2>SOL & Deadlines</h2>
    ${field('SOL Date', matter.sol_date ? fmtDate(matter.sol_date) : 'Not set')}
    ${matter.sol_date ? `<p style="font-size:9.5pt;color:#c53030;margin:4px 0 0;">⚠ Statute of Limitations deadline — calendar and docket immediately.</p>` : ''}

    <h2>Notes</h2>
    <div style="background:#f8f9fa;padding:10px 14px;border-radius:4px;font-size:10pt;white-space:pre-wrap;">${matter.notes || 'No notes.'}</div>`;

  return renderPdf(baseHtml('Matter Summary', body));
}

module.exports = { generateInvoicePdf, generateMatterSummaryPdf };
